import {Component} from '@angular/core';
@Component({standalone:true,template:`<section class="page"><div class="page-head"><div><h1>Roadmap TRAXUP</h1><p>Sequência de implementação consolidada em 09/09/2026</p></div></div><div class="roadmap">@for(r of phases;track r.name){<div class="card roadmap-card"><div class="phase-dot"></div><div class="phase-main"><div class="phase-head"><h2>{{r.name}}</h2><span class="badge">{{r.progress}}%</span></div><p>{{r.desc}}</p><div class="track"><i [style.width.%]="r.progress"></i></div><small>{{r.status}}</small></div></div>}</div></section>`})
export class RoadmapComponent {phases=[
{name:'FASE 1 — FUNDAÇÃO',desc:'Arquitetura, multi-tenant, autenticação/RBAC, PostgreSQL, migrations, Docker, CI/CD e padrões REST.',progress:85,status:'Estágio avançado'},
{name:'FASE 2 — FISCAL',desc:'Perfil fiscal → emissão NF-e/NFC-e → SEFAZ → retorno → rejeição/autorização → XML/DANFE → armazenamento.',progress:60,status:'Frente principal em implementação'},
{name:'FASE 3 — CADASTROS / PRODUTOS / ESTOQUE',desc:'Empresas, filiais, clientes, fornecedores, produtos, grades, NCM, preços, inventário e movimentações.',progress:55,status:'Em implementação'},
{name:'FASE 4 — FINANCEIRO',desc:'Contas a pagar/receber, caixa, DRE, boletos, recebíveis e conciliação de cartões.',progress:40,status:'Em implementação'},
{name:'FASE 5 — PDV',desc:'PDV Desktop, SQLite local, venda offline, caixa, impressão, últimas vendas, segunda tela e mesas/delivery.',progress:35,status:'Em implementação'},
{name:'FASE 6 — SINCRONIZAÇÃO / PAGAMENTOS',desc:'PDV ↔ nuvem, TEF/Payment Hub, PIX, POS integrado, Tap to Pay e conciliação.',progress:28,status:'Parcial / planejado'},
{name:'FASE 7 — SAAS / CONTABILIDADE',desc:'Planos, assinaturas, cobrança, trial, white-label, XML 5 anos, SPED e portal da contabilidade.',progress:25,status:'Planejado / parcial'},
{name:'FASE 8 — CRM / BI / MOBILE / INTEGRAÇÕES',desc:'CRM, fidelização, BI, relatórios dinâmicos, app vendedor, inventário mobile, iFood e marketplaces.',progress:15,status:'Planejado'},
{name:'FASE 9 — HOMOLOGAÇÃO / PRODUÇÃO',desc:'E2E, LGPD, segurança, observabilidade, performance, homologação fiscal e rollout comercial.',progress:20,status:'Transversal / em evolução'}];}